#ifndef ENUM_H
#define ENUM_H

enum TYPE_TOKEN {
    OPERATEUR, MOTCLE, IDENTIFIANT, TYPE
};

enum TYPE_INSTRUCTION {
    DEFINITION, TANTQUE, JUSQUE, POUR, SI, SELON, FIN, typeLigne_COUNT 
};

#endif