#ifndef ENUM_H
#define ENUM_H

typedef enum{
    OPERATEUR, MOTCLE, IDENTIFIANT, TYPE
} TYPE_TOKEN;

enum TYPE_INSTRUCTION {
    DEFINITION, TANTQUE, JUSQUE, POUR, SI, SELON, FIN, typeLigne_COUNT 
};

#endif